### ISSUE TITLE
Prepare Humus for use in CI

### ISSUE THREAD

**Issue by floere** [CocoaPods/Humus#11]
* [x] Upload sanitized/size-reduced DB dump to e.g. S3. (Using `pg_dump -Fc`)
* [x] Store the dump's location in Humus.
* [x] Enable the snapshot (dump) to be downloaded and loaded into the DB.
* [x] Add s3 as dependency on the Humus gem.
* [x] Gemify Humus.
* [x] Re-enable working snapshots to be used in search.
* [x] Polishing.
* [x] Release gem.
* [x] Add s3 credentials to … Admin?
* [x] Set up CI for search on Travis or Circle (@kylef).

### Example on gem `cocoapods-humus` usage

For the following example to work, both `ENV['DUMP_ACCESS_KEY_ID']` and `ENV['DUMP_SECRET_ACCESS_KEY']` need to be set.

In Gemfile:

```
gem 'cocoapods-humus', :require => false
```

In your e.g. spec_helper.rb / integration test:

```ruby
require 'cocoapods-humus'

# Non-block version.
Humus.with_snapshot('201510021730-b154')

# Block version.
Humus.with_snapshot('201510021730-b154') do
  # …
end
```

The gem is currently using the file system, and writing to a fixed DB with name `trunk_cocoapods_org_test`.
@kylef Let me know if that is an issue and we'll improve.

### Real world example 

1. Clone https://github.com/CocoaPods/search.cocoapods.org.
2. `bundle install`
3. `bundle exec rake`

Code is here: https://github.com/CocoaPods/search.cocoapods.org/blob/5d1781722e58cbb42d9dd0723f4852680aaf5070/spec/db_seed.rb#L3-L6

**Comment by kylef** [comment]
Great work @floere.

Does anyone have any preferences on Circle CI or Travis CI?

**Comment by floere** [comment]
Cheers!

Either is fine for me, as long as it has a DB and supports private env vars.

**Comment by floere** [comment]
Works: https://travis-ci.org/CocoaPods/search.cocoapods.org

**Comment by floere** [comment]
@kylef Sorry for barging ahead – I wanted to prepare CI a bit for you, and it just magically worked.

**Comment by kylef** [comment]
:boom:

**Comment by floere** [comment]
🌊
