### ISSUE TITLE
Add pod_version_id to cocoadocs_pod_metrics table

### ISSUE THREAD

**Issue by fulldecent** [CocoaPods/Humus#17]
Related to: https://github.com/CocoaPods/cocoadocs-api/issues/24#issuecomment-247816455

This additional field will allow tracking the recency of `cocoadocs_pod_metrics` data, which is necessary for reliable continuous integration.

**Comment by floere** [comment]
@fulldecent One nitpick: Call it `pod_version_id`.

**Comment by fulldecent** [comment]
Thank you, updated

**Comment by fulldecent** [comment]
To be clear, are you still accepting contributions to this project?? If so would a PR that fixes this be in scope to be merged?

**Comment by orta** [comment]
Probably not at this point, I don't want to be shaking any foundations now given the amount of time people have to maintain the web infra
